### ISSUE TITLE
显示问题

### ISSUE THREAD

**Issue by wudi-7mi** [TTopoo/RamboPlayYRLadderList#1]
当屏幕高度超过首批排名显示的高度（2k屏已经超出15名的高度了），无法加载下面的内容。
简而言之就是滚动刷新在不能滚动的情况下无法刷新

**Comment by TTopoo** [comment]
用暴力手段修好了 @wudi-7mi

**Comment by wudi-7mi** [comment]
![7d9bc93ab6788cb9b3235b2d97137f55](https://github.com/TTopoo/RamboPlayYRLadderList/assets/122330888/1c7624c4-30b2-425b-b175-d5393be36c2a)
![th](https://github.com/TTopoo/RamboPlayYRLadderList/assets/122330888/b702c97d-0055-4103-b251-e961d02b73a4)

**Comment by TTopoo** [comment]
> ![7d9bc93ab6788cb9b3235b2d97137f55](https://private-user-images.githubusercontent.com/122330888/285819427-1c7624c4-30b2-425b-b175-d5393be36c2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwODUwMTAsIm5iZiI6MTcwMTA4NDcxMCwicGF0aCI6Ii8xMjIzMzA4ODgvMjg1ODE5NDI3LTFjNzYyNGM0LTMwYjItNDI1Yi1iMTc1LWQ1MzkzYmUzNmMyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyN1QxMTMxNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZmFjMGZjZTAwMDgyNzNiODhlNTE2ZDYzN2Y2NzcyNjVlZWM0NWM1ZTIyMzcxM2ZjZjIwZjVhMzY3NGNlMmVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SoFZLBcKXyTCQKwg_XK2CDxSLKcieS0VhrUS_EyXyhY) ![th](https://private-user-images.githubusercontent.com/122330888/285819512-b702c97d-0055-4103-b251-e961d02b73a4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwODUwMTAsIm5iZiI6MTcwMTA4NDcxMCwicGF0aCI6Ii8xMjIzMzA4ODgvMjg1ODE5NTEyLWI3MDJjOTdkLTAwNTUtNDEwMy1iMjUxLWU5NjFkMDJiNzNhNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyN1QxMTMxNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOGQxOTU5N2Q0ZmQ5OGZmZDNhMzcxNGNiMTVmZTVmYWZmYzVhZDNlZmJkYWJiMjUxZjY5YWFlODEyYmE5ZDM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cPehYU9PI6CoEefpIV_LG1AxnMRz3IXg4VLFmVM_S94)

可以再试试

**Comment by wudi-7mi** [comment]
一百分
